code: 0
swordName: Sword of Summoning
swordSpecialSword: 1
swordSpecialPower: 10
candiesNbrOwned: 0
candiesNbrThrown: 5010
candiesNbrEaten: 802248822
candiesNbrTotal: 2204162309
candiesCandiesPerSecond: 13
candiesConverterActivated: 1
cauldronBookPage: 1
cauldronCandies: 0
cauldronLollipops: 0
chocolateBarsNbrOwned: 10
farmLollipopsPlanted: 200000
farmCurrentFlagIndex: 0
farmPlantingButtonsStep: 4
forgeStep: 2
shopLollipopsButtonsShown: 1
shopShown: 1
shopTicklingStep: 0
shopClickingOnLollipopStep: 0
hutStep: 2
hutSpeech: You can now summon a candy monster !
inventoryMagicianHatLetter:      w
lollipopsNbrOwned: 1402890751
lollipopsNbrInStock: 140
lollipopsNbrBought: 51
mainNbrOfSecondsSinceLastMinInterval: 24
mainNbrOfSecondsSinceLastHourInterval: 324
mainNbrOfSecondsSinceLastDayInterval: 7524
mountGoblinBasicChestProbability: 150
peacefulForestBasicChestProbability: 150
peacefulForestPoniesEncountered: 3
objectsHaveObjectKey: 1
objectsHaveObjectHutMap: 1
objectsHaveObjectWellMap: 1
objectsHaveObjectSwampMap: 1
objectsHaveObjectBoots: 1
objectsHaveObjectMagicianHat: 1
objectsHaveObjectPinkRing: 1
objectsHaveObjectForgeMap: 1
objectsHaveObjectCandiesConverter: 1
objectsHaveObjectPlateArmour: 1
objectsHaveObjectCauldron: 1
objectsHaveObjectMagicalHorn: 1
objectsHaveObjectHornOfPlenty: 1
objectsHaveObjectOldAmulet: 1
potionsShownHealth: 1
potionsShownEscape: 1
potionsShownBerserk: 1
potionsShownFireScroll: 1
potionsShownAcidRainScroll: 1
potionsShownTeleportScroll: 1
potionsShownEarthquakeScroll: 1
potionsShownImpInvocationScroll: 1
potionsShownMajorHealth: 1
potionsShownInvulnerability: 1
potionsShownTurtle: 1
potionsShownJelly: 1
potionsShownSeed: 1
potionsShownCloning: 1
potionsShownSuperman: 1
potionsShownGmooh: 1
potionsNbrOwnedHealth: 0
potionsNbrOwnedEscape: 8
potionsNbrOwnedBerserk: 0
potionsNbrOwnedFireScroll: 95
potionsNbrOwnedAcidRainScroll: 106
potionsNbrOwnedTeleportScroll: 52
potionsNbrOwnedEarthquakeScroll: 106
potionsNbrOwnedImpInvocationScroll: 104
potionsNbrOwnedMajorHealth: 29
potionsNbrOwnedInvulnerability: 32
potionsNbrOwnedTurtle: 5
potionsNbrOwnedJelly: 0
potionsNbrOwnedSeed: 9
potionsNbrOwnedCloning: 3
potionsNbrOwnedSuperman: 3
potionsNbrOwnedGmooh: 28
questMaxLandOrder: 12
questTiredTime: 0
spellsFasterCandiesFibo1: 13
spellsFasterCandiesFibo2: 21
swampStep: 17
tabsAnimation: slide
wishingWellSpeech: Here's 60 various potions and scrolls for you !!
wishingWellStep: 2
yourselfCanSurpass: 1
developperComputerWon: 1